# Site settings
title: Chelsey M. Beese, Ph.D.
email: beese.c.m@gmail.com
description: >
  Marine scientist, ecosystem modeler, and science communicator
baseurl: ""
url: ""

# Build settings
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Author
author:
  name: Chelsey M. Beese
  email: beese.c.m@gmail.com

# Minima settings
minima:
  social_links:
    - { platform: github, user_url: "https://github.com/cmbeese" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/chelseybeese/" }

# Header pages
header_pages:
  - about.md
  - cv.md
  - publications.md
  - projects.md
  - gallery.md
  - mizerreef.md

# Include _pages directory
include:
  - _pages

# Exclude
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - website-roadmap.txt
  - website-todo.txt
